Repository Polynomeer/baseball, pull requests merged in 2021-05, with the labels that each got.

#8 [BE] 환경설정 및 DB 설계
  BE/.gitignore
  BE/.idea/.gitignore
  BE/.idea/codeStyles/codeStyleConfig.xml
  BE/.idea/misc.xml
  BE/.idea/vcs.xml
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/com/codesquad/team12/baseball/BaseballApplication.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/banner.txt
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
  BE/src/test/java/com/codesquad/team12/baseball/BaseballApplicationTests.java
Labels: Backend, design, documentation

#9 Feature/6/intro home UI
  FE/baseball/public/index.html
  FE/baseball/src/App.js
  FE/baseball/src/Components/Home/Home.jsx
  FE/baseball/src/Components/Home/HomeStyles.jsx
  FE/baseball/src/Components/Home/HomeTitle.jsx
  FE/baseball/src/Components/Home/MatchInfo/MatchBox/GameNumber.jsx
  FE/baseball/src/Components/Home/MatchInfo/MatchBox/Match.jsx
  FE/baseball/src/Components/Home/MatchInfo/MatchBox/MatchBox.jsx
  FE/baseball/src/Components/Home/MatchInfo/MatchBox/TeamName.jsx
  FE/baseball/src/Components/Home/MatchInfo/MatchBox/VS.jsx
  FE/baseball/src/Components/Home/MatchInfo/MatchInfo.jsx
  FE/baseball/src/Components/Home/MatchInfo/MatchInfoBody.jsx
  FE/baseball/src/Components/Home/MatchInfo/MatchInfoTitle.jsx
  FE/baseball/src/Components/Intro/GameStartButton.jsx
  FE/baseball/src/Components/Intro/GameTitle.jsx
  FE/baseball/src/Components/Intro/Intro.jsx
  FE/baseball/src/Components/Intro/IntroStyles.jsx
  FE/baseball/src/Routes/Home.jsx
  FE/baseball/src/Routes/Intro.jsx
  FE/baseball/src/Routes/Router.jsx
  FE/baseball/src/Styles/CommonStyles.jsx
  FE/baseball/src/Styles/GlobalStyles.jsx
  FE/baseball/src/Styles/theme.js
  FE/baseball/yarn.lock
Labels: Frontend

#15 fix: Route game component (#14)
  FE/baseball/src/Components/Home/HomeStyles.jsx
  FE/baseball/src/Components/Home/MatchInfo/MatchBox/Match.jsx
Labels: Frontend, fix

#16 fix: Fix Game baackground (#13)
  FE/baseball/src/Components/Game/GameStyles.jsx
Labels: Frontend, fix

#18 refactor: Refactor styled-component (#17)
  FE/baseball/src/Components/Game/ScoreBoard/ScoreBoard.jsx
  FE/baseball/src/Components/Game/ScoreBoard/ScoreBoardStyles.jsx
  FE/baseball/src/Components/Home/HomeStyles.jsx
  FE/baseball/src/Components/Home/MatchInfo/MatchBox/GameNumber.jsx
  FE/baseball/src/Components/Home/MatchInfo/MatchBox/Match.jsx
  FE/baseball/src/Components/Home/MatchInfo/MatchBox/MatchBox.jsx
  FE/baseball/src/Components/Home/MatchInfo/MatchBox/TeamName.jsx
  FE/baseball/src/Components/Home/MatchInfo/MatchBox/VS.jsx
  FE/baseball/src/Components/Home/MatchInfo/MatchInfo.jsx
  FE/baseball/src/Components/Home/MatchInfo/MatchInfoBody.jsx
  FE/baseball/src/Components/Home/MatchInfo/MatchInfoTitle.jsx
Labels: Frontend, refactor

#23 [BE] 환경설정 및 DB 설계
  BE/.gitignore
  BE/.idea/.gitignore
  BE/.idea/codeStyles/codeStyleConfig.xml
  BE/.idea/misc.xml
  BE/.idea/vcs.xml
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/com/codesquad/team12/baseball/BaseballApplication.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/banner.txt
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
  BE/src/test/java/com/codesquad/team12/baseball/BaseballApplicationTests.java
Labels: Backend, design, documentation

#44 Feature/7/dto
  BE/src/main/java/com/codesquad/team12/baseball/controller/GameController.java
  BE/src/main/java/com/codesquad/team12/baseball/controller/MainController.java
  BE/src/main/java/com/codesquad/team12/baseball/dto/GameDto.java
  BE/src/main/java/com/codesquad/team12/baseball/dto/GameInitDto.java
  BE/src/main/java/com/codesquad/team12/baseball/dto/InningDto.java
  BE/src/main/java/com/codesquad/team12/baseball/dto/MainDto.java
  BE/src/main/java/com/codesquad/team12/baseball/dto/PlayerDto.java
  BE/src/main/java/com/codesquad/team12/baseball/dto/PlayingDto.java
  BE/src/main/java/com/codesquad/team12/baseball/dto/PlayingsDto.java
  BE/src/main/java/com/codesquad/team12/baseball/dto/ScoreDto.java
  BE/src/main/java/com/codesquad/team12/baseball/dto/ScoreTeamDto.java
  BE/src/main/java/com/codesquad/team12/baseball/dto/TeamDto.java
  BE/src/main/java/com/codesquad/team12/baseball/dto/TeamPlayerDto.java
  BE/src/main/java/com/codesquad/team12/baseball/model/Game.java
  BE/src/main/java/com/codesquad/team12/baseball/model/Inning.java
  BE/src/main/java/com/codesquad/team12/baseball/model/Player.java
  BE/src/main/java/com/codesquad/team12/baseball/model/Playing.java
  BE/src/main/java/com/codesquad/team12/baseball/model/Team.java
  BE/src/main/java/com/codesquad/team12/baseball/repository/GameRepository.java
  BE/src/main/java/com/codesquad/team12/baseball/repository/InningRepository.java
  BE/src/main/java/com/codesquad/team12/baseball/repository/PlayingRepository.java
  BE/src/main/java/com/codesquad/team12/baseball/repository/TeamRepository.java
  BE/src/main/java/com/codesquad/team12/baseball/service/GameService.java
  BE/src/main/java/com/codesquad/team12/baseball/service/InningService.java
  BE/src/main/java/com/codesquad/team12/baseball/service/PlayingService.java
  BE/src/main/java/com/codesquad/team12/baseball/service/TeamService.java
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
Labels: Backend, feature

#55 Feature/45/put
  BE/src/main/java/com/codesquad/team12/baseball/controller/GameController.java
  BE/src/main/java/com/codesquad/team12/baseball/controller/MainController.java
  BE/src/main/java/com/codesquad/team12/baseball/dto/request/InningRequestDto.java
  BE/src/main/java/com/codesquad/team12/baseball/dto/request/PlayingRequestDto.java
  BE/src/main/java/com/codesquad/team12/baseball/dto/response/GameDto.java
  BE/src/main/java/com/codesquad/team12/baseball/dto/response/GameInitDto.java
  BE/src/main/java/com/codesquad/team12/baseball/dto/response/InningDto.java
  BE/src/main/java/com/codesquad/team12/baseball/dto/response/MainDto.java
  BE/src/main/java/com/codesquad/team12/baseball/dto/response/PlayerDto.java
  BE/src/main/java/com/codesquad/team12/baseball/dto/response/PlayingDto.java
  BE/src/main/java/com/codesquad/team12/baseball/dto/response/PlayingsDto.java
  BE/src/main/java/com/codesquad/team12/baseball/dto/response/ScoreDto.java
  BE/src/main/java/com/codesquad/team12/baseball/dto/response/ScoreTeamDto.java
  BE/src/main/java/com/codesquad/team12/baseball/dto/response/TeamDto.java
  BE/src/main/java/com/codesquad/team12/baseball/dto/response/TeamPlayerDto.java
  BE/src/main/java/com/codesquad/team12/baseball/model/Game.java
  BE/src/main/java/com/codesquad/team12/baseball/model/Inning.java
  BE/src/main/java/com/codesquad/team12/baseball/model/Player.java
  BE/src/main/java/com/codesquad/team12/baseball/model/Playing.java
  BE/src/main/java/com/codesquad/team12/baseball/model/Team.java
  BE/src/main/java/com/codesquad/team12/baseball/repository/InningRepository.java
  BE/src/main/java/com/codesquad/team12/baseball/repository/PlayingRepository.java
  BE/src/main/java/com/codesquad/team12/baseball/service/GameService.java
  BE/src/main/java/com/codesquad/team12/baseball/service/InningService.java
  BE/src/main/java/com/codesquad/team12/baseball/service/PlayingService.java
  BE/src/main/java/com/codesquad/team12/baseball/service/TeamService.java
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
Labels: Backend, feature
